#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Modified 2015 by Freifunk Berlin
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Public and Admin LuCI UI
LUCI_DEPENDS:=community-profiles
LUCI_EXTRA_DEPENDS:=luci-mod-admin-full, luci-lib-json, luci-lib-ipkg, luci-compat
PKG_RELEASE:=1

include ../include-luci.mk

# call BuildPackage - OpenWrt buildroot signature
